---
title: "Report fish"
bibliography: citations.bib  
output:
  pdf_document: default
  html_document: default
fig_caption: TRUE
date: "18 February 2019"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
data <- read.csv("data/fish_lw.csv")
data <- data[!is.na(data$weight),]
```

## Introduction
Fish are great [@Schiettekatte2019].
Here, we analyze the relationship between length and weight of fish in French Polynesia.
bla bla
bla bla

## Methods
We killed a lot of fish by using spearguns. We then measured and weighed them.   

## Results

```{r}
# linear regression
lm <- lm(log(weight) ~ log(tl), data = data)
intercept <- lm$coefficients[[1]]
slope <- lm$coefficients[[2]]
lm_summary <- summary(lm)
table <- lm_summary$coefficients[,1:2]
rownames(table) <- c("intercept", "slope")
colnames(table) <- c("mean", "se")
knitr::kable(table)
```



```{r plot, ,fig.cap="Length-weight relationship"}
library(ggplot2)
plot <- 
ggplot(data)+
  geom_point(aes(log(tl), log(weight)))+
  geom_abline(slope = slope, intercept = intercept)+
  theme_bw()
plot
```

\newpage
## References

